baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = ["hugo-theme-massively", "hugo-shortcode-gallery"]


[[menu.nav]]
name = 'Gallery'
url = 'gallery/'
weight = 1
